; Pan/Tilt camera controller — ESP32-S3 + external RS485 Pelco-D/P pan-tilt head
; + 4" touch TFT (ST7796S, 480x320, XPT2046 resistive touch) + digital compass (QMC5883P)

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_port = COM11
monitor_port = COM11
monitor_rts = 0
monitor_dtr = 0
board_build.partitions = default_16MB.csv
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    paulstoffregen/XPT2046_Touchscreen
build_flags =
    -D CORE_DEBUG_LEVEL=1
    -D BOARD_HAS_PSRAM
